Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MusicDating.Models;
using MusicDating.Data;
using Microsoft.EntityFrameworkCore;
using MusicDating.Models.Entities;
using MusicDating.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using MusicDating.Models.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace MusicDating.Controllers
{
    public class ProfileController : Controller
    {
        // Access to the database
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public ProfileController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        [Authorize]
        public async Task<IActionResult> Index()
        {

            var user = await _userManager.GetUserAsync(User);
            // var Posts = await _context.Posts.Where(x => x.Id == user.Id).Include(x => x.EnsembleName).Include(x => x.Description).Include(y => y.Instrument).ThenInclude(y => y.Name).ToListAsync();
            var vm = new ProfileVm()
            {
                ApplicationUser = user,
                UserInstruments = await _context.UserInstruments.Where(y => y.ApplicationUser.Id == user.Id).Include(x => x.Instrument).Include(y => y.UserInstrumentGenres).ThenInclude(y => y.Genre).ToListAsync(),
                Posts = await _context.Posts.Where(x => x.ApplicationUser.Id == user.Id).Include(x => x.Instrument).ToListAsync(),

            };

            return View(vm);

        }

        public async Task<IActionResult> Edit()
        {

            ApplicationUser user = await _userManager.GetUserAsync(User);

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("FirstName,LastName,ProfileDescription")] ApplicationUser applicationUser)
        {

            ApplicationUser user = await _userManager.GetUserAsync(User);
            user.FirstName = applicationUser.FirstName;
            user.LastName = applicationUser.LastName;
            user.ProfileDescription = applicationUser.ProfileDescription;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicationUserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);

        }
        private bool ApplicationUserExists(string id)
        {
            return _context.ApplicationUsers.Any(e => e.Id == id);
        }

    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MusicDating.Models;
using MusicDating.Data;
using Microsoft.EntityFrameworkCore;
using MusicDating.Models.Entities;
using MusicDating.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using MusicDating.Models.Services;

namespace MusicDating.Controllers
{
    public class UsersController : Controller
    {
        // Access to the database
        private readonly ApplicationDbContext _context;

        public UsersController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string instrumentName, int genreId)
        {
            UserInstrumentVm vm = await UserServices.SearchForUsers(_context, instrumentName, genreId);

            return View(vm);
        }

        public async Task<IActionResult> Post(string instrumentName)
        {
            PostVm viewmodel = await PostServices.SearchForPost(_context, instrumentName);

            return View(viewmodel);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MusicDating</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <div class="navbar-logo">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Musik Samspil</a>
                    <p class="navbar-dao">Skabt af DAOS - Dansk Amatørorkester Samvirke</p>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon black-text" onclick="navbarCollapse()"></span>
                </button>
                <div class="navbar-collapse collapse flex-sm-row-reverse text-center">

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Hjem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Users" asp-action="Index">Find musiker</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Users" asp-action="Post">Find
                                ensemble</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Profile" asp-action="Index">Profil</a>
                        </li>
                    </ul>
                    <br>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container footer-container">
            <div class="index-content">
                <div class=footer>
                    <h2>MUSIK SAMSPIL</h2>
                    <ul>
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Hjem</a></li>
                        <li><a asp-area="" asp-controller="Users" asp-action="Index">Find musiker</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Find ensemble</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Profil</a></li>
                    </ul>
                    <div class="row">
                        <div class="col-1">
                            <img src="/images/icons8-instagram.svg" alt="Instagram">
                        </div>
                        <div class="col-1">
                            <img src="/images/icons8-facebook_old.svg" alt="Facebook">
                        </div>
                    </div>
                    <div class="footer-img">
                        <img src="/images/pale-30.svg" alt="footer">
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>